import img1 from '../../../assets/img/ourWork/1 (1).png'
import img2 from '../../../assets/img/ourWork/12.png'
import img3 from '../../../assets/img/ourWork/3.png'
import img4 from '../../../assets/img/ourWork/3colo.jpg'
import img5 from '../../../assets/img/ourWork/5 (2).png'
import img6 from '../../../assets/img/ourWork/7.png'
import img7 from '../../../assets/img/ourWork/Emily_Hair_Preview_05.png'
import img8 from '../../../assets/img/ourWork/Emily_Hair_Preview_Thumbnail_04 (2).png'
import img9 from '../../../assets/img/ourWork/Tex.jpg'
import img10 from '../../../assets/img/ourWork/VIKING WOMAN - HalfBody1.jpg'
import img11 from '../../../assets/img/ourWork/VIKING WOMAN - Halfbody (2).jpg'
import img12 from '../../../assets/img/ourWork/VIKING WOMAN - Hires Props.jpg'
import img13 from '../../../assets/img/ourWork/VIKING WOMAN - Thumbnail.jpg'
import img14 from '../../../assets/img/ourWork/b (1).jpg'
import img15 from '../../../assets/img/ourWork/b (10).jpg'
import img16 from '../../../assets/img/ourWork/b (13).jpg'
import img17 from '../../../assets/img/ourWork/christopher-goh-1.jpg'
import img18 from '../../../assets/img/ourWork/christopher-goh-2.jpg'
import img19 from '../../../assets/img/ourWork/christopher-goh-4.jpg'
import img20 from '../../../assets/img/ourWork/fish (1).jpg'
import img21 from '../../../assets/img/ourWork/fiship.jpg'
import img22 from '../../../assets/img/ourWork/nuke001.jpg'
import img23 from '../../../assets/img/ourWork/old.jpg'
import img24 from '../../../assets/img/ourWork/wkw.jpg'
import img25 from '../../../assets/img/ourWork/ort.jpg'
import img26 from '../../../assets/img/ourWork/witch/christopher-goh-back.jpg'
import img27 from '../../../assets/img/ourWork/witch/christopher-goh-flow (1).jpg'
import img28 from '../../../assets/img/ourWork/witch/christopher-goh-kb.jpg'
import img29 from '../../../assets/img/ourWork/witch/christopher-goh-leo.jpg'
import img30 from '../../../assets/img/ourWork/witch/christopher-goh-tes.jpg'
import img31 from '../../../assets/img/ourWork/witch/christopher-goh-wbitch.jpg'
import img32 from '../../../assets/img/ourWork/witch/christopher-goh-witchbitch.jpg'

export const OurWorkData = [img1, img2, img3, img4, img5, img6, img7, img8, img9, img10, img11, img12, img13, img14, img15, img16, img17, img18, img19, img20, img21, img22, img23, img24, img25, img26, img27, img28, img29, img30, img31, img32]
 